### ISSUE TITLE
Cannot build from source to use integration UI

### ISSUE THREAD

**Issue by s123-afk** [Farama-Foundation/stable-retro#108]
>  git clone https://github.com/Farama-Foundation/stable-retro.git
> cd stable-retro
> pip3 install -e .

### after I tried the above command, this is the error message:

(stanley) stanley@MSI:~/gymRetro/stable-retro$ pip install -e .
Obtaining file:///home/stanley/gymRetro/stable-retro
   Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: gymnasium>=0.27.1 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from stable-retro==0.9.3) (0.29.1)
Requirement already satisfied: pyglet==1.*,>=1.3.2 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from stable-retro==0.9.3) (1.5.28)
Requirement already satisfied: farama-notifications>=0.0.1 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from stable-retro==0.9.3) (0.0.4)
Requirement already satisfied: numpy>=1.21.0 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from gymnasium>=0.27.1->stable-retro==0.9.3) (1.26.3)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from gymnasium>=0.27.1->stable-retro==0.9.3) (3.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages (from gymnasium>=0.27.1->stable-retro==0.9.3) (4.9.0)
Building wheels for collected packages: stable-retro
  Building editable for stable-retro (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for stable-retro (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [399 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info
      writing /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.dylib' found anywhere in distribution
      warning: no previously-included files matching '*-version' found under directory 'retro/cores'
      adding license file 'LICENSE'
      adding license file 'LICENSES.md'
      writing manifest file '/tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro-0.9.3.dist-info'
      creating /tmp/pip-wheel-7_4ullp0/.tmp-ier8au9m/stable_retro-0.9.3.dist-info/WHEEL
      running build_py
      running build_ext
      CMake Warning:
        Ignoring empty string ("") provided on the command line.
      
      
      CMake Warning:
        Ignoring empty string ("") provided on the command line.
      
      
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
      CMake Deprecation Warning at third-party/capnproto/c++/CMakeLists.txt:2 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Warning at CMakeLists.txt:306 (message):
        Could not find CapnProto, disabling search save/load
      
      
      CMake Deprecation Warning at third-party/libzip/CMakeLists.txt:5 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Deprecation Warning at third-party/gtest/googlemock/CMakeLists.txt:46 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Deprecation Warning at third-party/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Warning (dev) at third-party/gtest/googletest/cmake/internal_utils.cmake:213 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        third-party/gtest/googletest/CMakeLists.txt:65 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Configuring done (5.1s)
      CMake Warning at CMakeLists.txt:361 (add_library):
        Cannot generate a safe linker search path for target retro because files in
        some directories may conflict with libraries in implicit directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at CMakeLists.txt:361 (add_library):
        Cannot generate a safe runtime search path for target retro because files
        in some directories may conflict with libraries in implicit directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-data because
        files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-data because
        files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-emulator because
        files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-emulator because
        files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-memory-overlay
        because files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-memory-overlay
        because files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-memory because
        files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-memory because
        files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-script because
        files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-script because
        files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe linker search path for target test-search because
        files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at tests/CMakeLists.txt:6 (add_executable):
        Cannot generate a safe runtime search path for target test-search because
        files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at src/ui/CMakeLists.txt:40 (add_executable):
        Cannot generate a safe linker search path for target gym-retro-integration
        because files in some directories may conflict with libraries in implicit
        directories:
      
          link library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      CMake Warning at src/ui/CMakeLists.txt:40 (add_executable):
        Cannot generate a safe runtime search path for target gym-retro-integration
        because files in some directories may conflict with libraries in implicit
        directories:
      
          runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
            /home/stanley/miniconda3/envs/stanley/lib
      
        Some of these libraries may not be found correctly.
      
      
      -- Generating done (0.2s)
      -- Build files have been written to: /home/stanley/gymRetro/stable-retro
      [  0%] Generating retro/cores/genesis_plus_gx-version
      [  0%] Generating retro/cores/fceumm-version
      [  0%] Generating retro/cores/stella-version
      [  0%] Generating retro/cores/snes9x-version
      [  0%] Generating retro/cores/mgba-version
      [  0%] Generating retro/cores/fceumm.json
      [  0%] Generating retro/cores/genesis_plus_gx.json
      [  0%] Generating retro/cores/mednafen_pce_fast-version
      [  0%] Generating retro/cores/snes9x.json
      [  4%] Generating retro/cores/stella.json
      [  4%] Generating retro/cores/genesis_plus_gx_libretro.so
      [  4%] Generating retro/cores/fceumm_libretro.so
      [  8%] Generating retro/cores/mgba.json
      [  8%] Generating retro/cores/snes9x_libretro.so
      [  8%] Generating retro/cores/mednafen_pce_fast.json
      [  8%] Generating retro/cores/stella_libretro.so
      [  8%] Generating retro/cores/mgba_libretro.so
      [ 12%] Generating retro/cores/mednafen_pce_fast_libretro.so
      [ 12%] Generating retro/cores/gambatte-version
      [ 12%] Generating retro/cores/gambatte.json
      [ 12%] Generating retro/cores/gambatte_libretro.so
      [ 12%] Built target snes
      [ 12%] Built target gba
      [ 12%] Built target pce
      [ 12%] Built target genesis
      [ 12%] Built target nes
      [ 12%] Generating retro/cores/mednafen_saturn-version
      [ 12%] Generating retro/cores/picodrive-version
      [ 12%] Built target gb
      [ 16%] Generating retro/cores/mednafen_saturn_libretro.so
      [ 16%] Generating retro/cores/mednafen_saturn.json
      [ 16%] Generating retro/cores/picodrive_libretro.so
      [ 16%] Generating retro/cores/picodrive.json
      [ 16%] Built target atari2600
      [ 16%] Linking C static library libzip.a
      [ 16%] Built target saturn
      [ 16%] Built target 32x
      [ 91%] Built target zip
      [ 91%] Linking CXX static library libretro-base.a
      [100%] Built target retro-base
      [100%] Linking CXX shared library retro/_retro.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: cannot find /lib64/libc.so.6: No such file or directory
      /usr/bin/ld: cannot find /usr/lib64/libc_nonshared.a: No such file or directory
      collect2: error: ld returned 1 exit status
      make[3]: *** [CMakeFiles/retro.dir/build.make:102: retro/_retro.cpython-310-x86_64-linux-gnu.so] Error 1
      make[2]: *** [CMakeFiles/Makefile2:1006: CMakeFiles/retro.dir/all] Error 2
      make[1]: *** [CMakeFiles/Makefile2:1013: CMakeFiles/retro.dir/rule] Error 2
      make: *** [Makefile:485: retro] Error 2
      Traceback (most recent call last):
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 62, in run
        File "/home/stanley/miniconda3/envs/stanley/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-j8', 'retro']' returned non-zero exit status 2.
      /tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `stable-retro` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/stanley/miniconda3/envs/stanley/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 436, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 84, in <module>
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-hnjez3r7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 62, in run
        File "/home/stanley/miniconda3/envs/stanley/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-j8', 'retro']' returned non-zero exit status 2.
      [end of `output]  `
  

## System information

- [Ubuntu 22.04.3 ]
- [Python 3.10.13]
- [Gym Retro 0.9.2]

**Comment by MatPoliquin** [comment]
Was it on a fresh install?
Which setup cmds did you run before installing stable-retro?
