### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by Misteridk2022** [Farama-Foundation/stable-retro#72]
## Issue summary
**For some reason am trying to install stable-retro through CMD and pycharm, but for some reason it's not working. I've updated setuptools and pip, reinstall them, unistalled everyone thing (Python and Pycharm) restart my computer few times install Cmake, Microsoft C++ build tools, and even have the require version of python to be compatiable for stable-retro I need your help.**

C:\Windows\System32>pip install stable-retro
Collecting stable-retro
  Using cached stable-retro-0.9.1.tar.gz (111.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\skyle\AppData\Local\Temp\pip-install-k9ez_2cs\stable-retro_1a174f8f15d44d96800ab359d52b65cb\setup.py", line 88, in <module>
          version=open(VERSION_PATH).read().strip(),
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\skyle\\AppData\\Local\\Temp\\pip-install-k9ez_2cs\\stable-retro_1a174f8f15d44d96800ab359d52b65cb\\retro/VERSION.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## System information

GPU
NVIDIA GeForce RTX 2070

Processor	
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)

Window 11
Python 3.8
stable-retro v0.9.1

**Comment by pseudo-rnd-thoughts** [comment]
`'C:\Users\skyle\AppData\Local\Temp\pip-install-k9ez_2cs\stable-retro_1a174f8f15d44d96800ab359d52b65cb\retro/VERSION.txt'` due to window using `\` rather than `/` in the path is wrong. 
I suspect we should use `os.path.join` rather than string concatenation

@zbeucler2018 would you be able to investigate?

**Comment by Misteridk2022** [comment]
hmm if that's the issue What can I do to change it or another method to install it?

**Comment by pseudo-rnd-thoughts** [comment]
Without you / us fixing it or you changing a linux based system then I don't think there is anything you can do.

**Comment by rizvi-ha** [comment]
Also having the same issue, is there a quick fix for the slash going the wrong way?

**Comment by zbeucler2018** [comment]
> `'C:\Users\skyle\AppData\Local\Temp\pip-install-k9ez_2cs\stable-retro_1a174f8f15d44d96800ab359d52b65cb\retro/VERSION.txt'` due to window using `\` rather than `/`, the path is wrong. 
> 
> I suspect we should use `os.path.join` rather than string concatenation
> 
> 
> 
> @zbeucler2018 would you be able to investigate?



I'm happy to investigate this and I think using os.join us a much better solution. However, I am not sure if we support windows

**Comment by pseudo-rnd-thoughts** [comment]
> However, I am not sure if we support windows 

Yes, is the simplest solution and Gymnasium doesn't officially support windows. 
Our general rule has been if we can make simple changes to support windows then we will otherwise no

**Comment by Misteridk2022** [comment]
So far, I've tried pip install stable-retro --pre, pip3 install stable-retro, and pip install stable-retro --use-pep517 with no luck. still showing the error.

**Comment by MatPoliquin** [comment]
> hmm if that's the issue What can I do to change it or another method to install it?

You can use WSL2 (Windows sur Subsystem for Linux) on Windows with Ubuntu 22.04 virtual machine and install stable-retro in the VM. It's works quite well and will be much less painful than running directly on Windows.

Here is a simple video for that:
[https://www.youtube.com/watch?v=28Ei63qtquQ](https://www.youtube.com/watch?v=28Ei63qtquQ)

**Comment by paulo101977** [comment]
> ## Issue summary
> **For some reason am trying to install stable-retro through CMD and pycharm, but for some reason it's not working. I've updated setuptools and pip, reinstall them, unistalled everyone thing (Python and Pycharm) restart my computer few times install Cmake, Microsoft C++ build tools, and even have the require version of python to be compatiable for stable-retro I need your help.**
> 
> C:\Windows\System32>pip install stable-retro Collecting stable-retro Using cached stable-retro-0.9.1.tar.gz (111.4 MB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\skyle\AppData\Local\Temp\pip-install-k9ez_2cs\stable-retro_1a174f8f15d44d96800ab359d52b65cb\setup.py", line 88, in version=open(VERSION_PATH).read().strip(), FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\skyle\AppData\Local\Temp\pip-install-k9ez_2cs\stable-retro_1a174f8f15d44d96800ab359d52b65cb\retro/VERSION.txt' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> 
> ## System information
> GPU NVIDIA GeForce RTX 2070
> 
> Processor Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
> 
> Window 11 Python 3.8 stable-retro v0.9.1

For me:

CMake Warning:
        Ignoring empty string ("") provided on the command line.


      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- The C compiler identification is GNU 14.1.0
      -- The CXX compiler identification is GNU 14.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could NOT find Python (missing: Development.Module) (found suitable version "3.10.0", minimum required is "3")
      -- Found ZLIB: C:/Program Files/zlib/lib/zlib.lib (found version "1.3.1")
      -- Found PkgConfig: C:/msys64/usr/bin/pkg-config.exe (found version "2.3.0")
      CMake Deprecation Warning at third-party/capnproto/c++/CMakeLists.txt:2 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Looking for C++ include initializer_list
      -- Looking for C++ include initializer_list - found
      CMake Warning at CMakeLists.txt:306 (message):
        Could not find CapnProto, disabling search save/load


      CMake Deprecation Warning at third-party/libzip/CMakeLists.txt:5 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Looking for _chmod
      -- Looking for _chmod - found
      -- Looking for _close
      -- Looking for _close - found
      -- Looking for _dup
      -- Looking for _dup - found
      -- Looking for _fdopen
      -- Looking for _fdopen - found
      -- Looking for _fileno
      -- Looking for _fileno - found
      -- Looking for _open
      -- Looking for _open - found
      -- Looking for _setmode
      -- Looking for _setmode - found
      -- Looking for _snprintf
      -- Looking for _snprintf - found
      -- Looking for _strdup
      -- Looking for _strdup - found
      -- Looking for _stricmp
      -- Looking for _stricmp - found
      -- Looking for _strtoi64
      -- Looking for _strtoi64 - found
      -- Looking for _strtoui64
      -- Looking for _strtoui64 - found
      -- Looking for _umask
      -- Looking for _umask - found
      -- Looking for _unlink
      -- Looking for _unlink - found
      -- Looking for clonefile
      -- Looking for clonefile - not found
      -- Looking for explict_bzero
      -- Looking for explict_bzero - not found
      -- Looking for explicit_memset
      -- Looking for explicit_memset - not found
      -- Looking for fileno
      -- Looking for fileno - found
      -- Looking for fseeko
      -- Looking for fseeko - found
      -- Looking for ftello
      -- Looking for ftello - found
      -- Looking for getprogname
      -- Looking for getprogname - not found
      -- Looking for open
      -- Looking for open - found
      -- Looking for mkstemp
      -- Looking for mkstemp - found
      -- Looking for setmode
      -- Looking for setmode - found
      -- Looking for snprintf
      -- Looking for snprintf - found
      -- Looking for strcasecmp
      -- Looking for strcasecmp - found
      -- Looking for strdup
      -- Looking for strdup - found
      -- Looking for stricmp
      -- Looking for stricmp - found
      -- Looking for strtoll
      -- Looking for strtoll - found
      -- Looking for strtoull
      -- Looking for strtoull - found
      -- Looking for include file fts.h
      -- Looking for include file fts.h - not found
      -- Looking for include file stdbool.h
      -- Looking for include file stdbool.h - found
      -- Looking for include file strings.h
      -- Looking for include file strings.h - found
      -- Looking for include file unistd.h
      -- Looking for include file unistd.h - found
      -- Looking for include file inttypes.h
      -- Looking for include file inttypes.h - found
      -- Looking for include file stdint.h
      -- Looking for include file stdint.h - found
      -- Looking for include file sys/types.h
      -- Looking for include file sys/types.h - found
      -- Looking for sys/types.h
      -- Looking for sys/types.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of __int8
      -- Check size of __int8 - done
      -- Check size of int8_t
      -- Check size of int8_t - done
      -- Check size of uint8_t
      -- Check size of uint8_t - done
      -- Check size of __int16
      -- Check size of __int16 - done
      -- Check size of int16_t
      -- Check size of int16_t - done
      -- Check size of uint16_t
      -- Check size of uint16_t - done
      -- Check size of __int32
      -- Check size of __int32 - done
      -- Check size of int32_t
      -- Check size of int32_t - done
      -- Check size of uint32_t
      -- Check size of uint32_t - done
      -- Check size of __int64
      -- Check size of __int64 - done
      -- Check size of int64_t
      -- Check size of int64_t - done
      -- Check size of uint64_t
      -- Check size of uint64_t - done
      -- Check size of short
      -- Check size of short - done
      -- Check size of int
      -- Check size of int - done
      -- Check size of long
      -- Check size of long - done
      -- Check size of long long
      -- Check size of long long - done
      -- Check size of off_t
      -- Check size of off_t - done
      -- Check size of size_t
      -- Check size of size_t - done
      -- Check size of ssize_t
      -- Check size of ssize_t - done
      -- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
      -- Looking for getopt
      -- Looking for getopt - found
      CMake Deprecation Warning at third-party/gtest/googlemock/CMakeLists.txt:46 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      

      CMake Deprecation Warning at third-party/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      CMake Warning (dev) at third-party/gtest/googletest/cmake/internal_utils.cmake:213 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        third-party/gtest/googletest/CMakeLists.txt:65 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: D:/projects/chess-environment/my-env/Scripts/python.exe (found version "3.10")
      CMake Error at CMakeLists.txt:387 (add_subdirectory):
        add_subdirectory given source "tests" which is not an existing directory.


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "D:\projects\chess-environment\my-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\projects\chess-environment\my-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\projects\chess-environment\my-env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\build_meta.py", line 403, in _build_with_temp_dir        
          self.run_setup()
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 84, in <module>
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\paulo\AppData\Local\Temp\pip-build-env-hhg5an6d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 39, in run
        File "D:\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '.', '-G', 'Unix Makefiles', '', '-DPYEXT_SUFFIX=.cp310-win_amd64.pyd', '-DPYLIB_DIRECTORY=build\\lib.win-amd64-cpython-310', '-DPython_ROOT_DIR=D:\\projects\\chess-environment\\my-env\\Scripts', '-DPython_FIND_STRATEGY=LOCATION', '-DPython_EXECUTABLE=D:\\projects\\chess-environment\\my-env\\Scripts\\python.exe', '-DPython_INCLUDE_DIR=D:\\Python310\\Include', '-DPython_LIBRARY=D:\\projects\\chess-environment\\my-env\\Lib\\site-packages']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stable-retro
Failed to build stable-retro
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (stable-retro)

**Comment by MatPoliquin** [comment]
For now we only support Windows through WSL2 since it works quite well and supporting/maintaining Windows directly will take a substantial amount of resources that will be better spent elsewhere
